### ISSUE TITLE
Two Songs on different Albums can look like they are on the same Album

### ISSUE THREAD

**Issue by bkw7** [djmailhot/BeatTide#28]
Since there is a lookup done by only the name of the album during the creation of the song, songs on albums with the same name appear to be on the same album, even if they are not the same album. 

To reproduce: Create a Song, Album, Artist combo with the SongsController, then create a different Song, Album, Artist combo with the same Album name.  If the album's .songs field is called, it looks like there are 2 songs on the Album, but they aren't necessarily on the same Album, the Albums just have the same name.

**Comment by mwinstanley** [comment]
Fixed - using album and artist IDs
