### ISSUE TITLE
Validation in the User Controller

### ISSUE THREAD

**Issue by hsingh09** [djmailhot/BeatTide#31]
In the show method:
- Users should not be able to see other users information unless they are signed in.  
- If show is called with an invalid ID it should fail using flash.now

In the create method
- Should fail if user has no first name, last name, username, or facebook ID.  

In the edit method
- Should fail if you are editing a user that is not you
- If invalid ID is passed should fail
- Should fail if you are not signed in

In the Index Method
- Should redirect to login if you are not signed in

**Comment by djmailhot** [comment]
Correct validation implemented.  A redirect is in place for unauthorized actions
