### ISSUE TITLE
User validation not working properly

### ISSUE THREAD

**Issue by rigsbyt** [djmailhot/BeatTide#39]
User username validation should fail on:

duplicates
<4 or >25 characters

facebook_id validation should fail on:

negative number

likes validation should fail on:

nonzero

Currently all these situations are allowed.

Steps to reproduce: Run the rspec tests. They indicate that users can be created under any of these situations.

**Comment by rigsbyt** [comment]
Much of this seems to be fixed. You can't set your username to be too long, and we no longer care about duplicate usernames. It looks like we're not validating age, since you can set it to a negative number.

**Comment by mwinstanley** [comment]
Fixed - except for age, which we aren't using.
