### ISSUE TITLE
SongsController tests show that songs, artists, and albums are not being successfully created

### ISSUE THREAD

**Issue by rigsbyt** [djmailhot/BeatTide#42]
The SongsController rspec tests are showing that songs, artists, and albums are not being successfully created. It is unclear to me whether this is a bug in the code or tests.

Steps to reproduce: run the rspec tests. It shows that none of these things are being successfully created.

**Comment by bkw7** [comment]
Yea I had that problem too but the tests are ok I'll fix it before the beta.
On Feb 21, 2012 9:55 PM, "rigsbyt" <
reply@reply.github.com>
wrote:

**Comment by mwinstanley** [comment]
Fixed.
