### ISSUE TITLE
Plus button should not appear in a song that you have already added.

### ISSUE THREAD

**Issue by alexdmiller** [djmailhot/BeatTide#44]
Steps to replicate:

Search for a song and press the green plus button. The song will be added to your collection, but the song in your collection will also have a green plus button. It should either disappear, or be replaced with a delete button.

**Comment by mwinstanley** [comment]
What is "your collection"? I feel like you should be able to post a song twice if you want; is there a difference between your posts and your "collection"?

**Comment by alexdmiller** [comment]
What I meant by "your collection" is the list of songs that you have
already posted. It's strange to have plus buttons on all of those I
think, because it just re-adds the song. I guess it also does make
sense to be able to add a song again....

Maybe we want to have a distinction between adding a song from a
search, and "re-blogging" a song from someone's (including your own)
post?

**Comment by alexdmiller** [comment]
Looks like someone fixed this; thanks!
