### ISSUE TITLE
TODO: Finalize and deploy Zero Feature Release

### ISSUE THREAD

**Issue by djmailhot** [djmailhot/BeatTide#5]
Make sure we have a version deployed that demonstrates just how incredibly awesome our website is eventually going to be.

**Comment by mwinstanley** [comment]
Completed - deployed to Heroku

**Comment by djmailhot** [comment]
is the deployed version the most recent commit on master?

On 6 February 2012 15:26, mwinstanley <
reply@reply.github.com
