### ISSUE TITLE
Unable to change username

### ISSUE THREAD

**Issue by mwinstanley** [djmailhot/BeatTide#50]
Description:
A user should be able to set their username. They should also be able to hide their real name.

Steps to reproduce:
Sign in with BeatTide

Expected behavior:
Some kind of link to user options page that allows you to edit your username

Actual behavior:
You are stuck with your FB username, and there is no link to user options

Proposed solution:
Have a user options page.

**Comment by djmailhot** [comment]
Implemented user edit profile
