### ISSUE TITLE
No help for a new user

### ISSUE THREAD

**Issue by mwinstanley** [djmailhot/BeatTide#51]
Description:
BeatTide should be easy to use on the very first visit, with helpful hints or a "FAQ" page or a tutorial.

Steps to reproduce:
Sign in to BeatTide as a new user for the very first time.

Expected behavior:
BeatTide presents a helpful welcome message, and links to a tutorial

Actual behavior:
BeatTide presents an empty search box, no posts, and no subscribed users, with no helpful messages or links

Proposed solution:
Helpful welcome message. FAQ page. Brief tutorial. "About" page.

**Comment by rigsbyt** [comment]
Alex implemented help button. First run experience pushed from V1.
