### ISSUE TITLE
Unable to view users you are subscribed to

### ISSUE THREAD

**Issue by mwinstanley** [djmailhot/BeatTide#56]
Description:
You should be able to view all your subscriptions, and have an easy means to unsubscribe.

Steps to reproduce:
Login to BeatTide
Subscribe to many users

Expected behavior:
There should be a link to "all subscriptions" with unsubscribe links for each subscription

Actual behavior:
No such link. Must visit each user's profile manually to remove subscriptions.

**Comment by rigsbyt** [comment]
Pushed!
