### ISSUE TITLE
Consider 3 column layout

### ISSUE THREAD

**Issue by alexdmiller** [djmailhot/BeatTide#60]
Our front page is quickly filling up with content. It might be a good design decision to widen the content area to contain three columns.

**Comment by djmailhot** [comment]
where are our advertisements going again?  I imagined all that empty space could be used for such a thing

**Comment by alexdmiller** [comment]
That's true. Advertisements could actually be interspersed in the columns actually.

**Comment by rigsbyt** [comment]
Considered.
