### ISSUE TITLE
Pagination of the search result (Grooveshark songs)

### ISSUE THREAD

**Issue by mwinstanley** [djmailhot/BeatTide#68]
Steps to reproduce:
Search for a song. Observe that there are only 10 results.

Desired behavior:
"More songs' link for more songs

**Comment by rigsbyt** [comment]
How many results should be on each subsequent page for this scenario,
keeping in mind that we'd have to load all of them into the database?

On Sun, Mar 4, 2012 at 6:52 PM, mwinstanley <
reply@reply.github.com

**Comment by mwinstanley** [comment]
Maybe 10, like we have right now?

**Comment by rigsbyt** [comment]
Won't fix for V1. Requires making a much larger query and doing pagination using AJAX. Results will almost always be in the top 10, because tinysong search is pretty good.
