### ISSUE TITLE
JavaScript is served in plain source

### ISSUE THREAD

**Issue by aryann** [djmailhot/BeatTide#71]
The JavaScript that is served contains comments/names. All JavaScript should be compiled to remove this. Compilers can also minify the size of the scripts.

You can use the Closure JS compiler:

https://developers.google.com/closure/compiler/

**Comment by djmailhot** [comment]
Wow!  This might be a true milestone of BeatTide popularity:  someone not on the team filing an issue on Github!  Nice one Aryan!

**Comment by mwinstanley** [comment]
Will not fix. Our app is open source anyway.
