### ISSUE TITLE
Make it more clear that the user cannot like his/her own post

### ISSUE THREAD

**Issue by bkw7** [djmailhot/BeatTide#74]
The like button for the user's own posts appears to be clickable, when it might be better to remove the like button for the user's own posts.

**Comment by mwinstanley** [comment]
I think this is OK, actually - Facebook does it! Is it really a problem?

**Comment by bkw7** [comment]
I was just under the impression that we weren't allowed to like our own posts because someone could just add songs and like them to get a higher like count, which would sort of ruin our overall user likes system.  If this is the case then I thought we wouldn't want to make the "like" button appear to be clickable for a users own posts since the user cannot interact with it.

**Comment by djmailhot** [comment]
Actually, since liking posts also increases the like count of the song, a user should be able to like their own post.  However, whether that increases the like count of the user himself?  Getting this grainy becomes slightly convoluted when destroying a post.

**Comment by alexdmiller** [comment]
We could rate users based on their like-to-post ratio rather than just likes?

**Comment by mwinstanley** [comment]
Actually, I'm seeing the problem now. What about if we allow users to like their own posts, but only have it apply to the post and the song?

**Comment by djmailhot** [comment]
With this special case, I previously mentioned that it would would get a little hairy when destroying a post.  I retract that statement.  It would be easy to do.  Is this what we want?  It just means a user's likes is the number of OTHER users that like you, not a total aggregate number (if we want to vebalize that on the UI or not, well, whatever)

**Comment by mwinstanley** [comment]
Fixed. A user can like their own posts, but these likes do not count toward their total user likes.

**Comment by bkw7** [comment]
Reach?

## 

# 

This mobile text message is brought to you by AT&T

**Comment by alexdmiller** [comment]
Wowwwwwww
