### ISSUE TITLE
User like count not displayed in search results

### ISSUE THREAD

**Issue by hsingh09** [djmailhot/BeatTide#76]
In the users results list it does not indicate how many likes the user has. 

Steps to Reproduce: Search for a user, see that the results page says " Likes"

Possible Error: Either the search results page does not link to the likes count correctly, or likes count is not initialized to 0 so it's displaying a null value (essentially "").

**Comment by djmailhot** [comment]
Not initialized to 0.  Alex turned this off.  Something about each time a Song is posted it is set back to 0.  However, I think the init functionality in the model could be more intelligent than this.

**Comment by alexdmiller** [comment]
Melissa fixed this. Likes are not initialized to 0 when a new user is created.

**Comment by djmailhot** [comment]
Wait a minute.  Yes the song is init'ed with like_count = 0.  It's in find_or_create(attributes....)

It's probably the linking to likes.

**Comment by alexdmiller** [comment]
Melissa made that fix. It wasn't there before. I think we have to reset the database or manually set everyone's likes to 0 now in production.

**Comment by alexdmiller** [comment]
Okay! Fixed for reals now on production.
