### ISSUE TITLE
Like link on posts no longer works, all posts have like count of 0

### ISSUE THREAD

**Issue by djmailhot** [djmailhot/BeatTide#77]
Repro:
Navigate to beattide.herokuapp.com and sign in
Try to like a song

Result:
No visible change

In the Console:
POST http://beattide.herokuapp.com/posts/like 500 (Internal Server Error)

**Comment by alexdmiller** [comment]
This has been fixed in the codebase. It's because we all have "Like" in our likes field right now, rather than an integer. I will fix the database. Note this only happens in production, not locally.

**Comment by alexdmiller** [comment]
Argh, I can't run the heroku rails console from the coffee shop I'm at, so I'm reopening this until it's actually fixed in production.

**Comment by alexdmiller** [comment]
Fixed on production.
