### ISSUE TITLE
"Flash" of front page content on first load

### ISSUE THREAD

**Issue by alexdmiller** [djmailhot/BeatTide#80]
Steps to reproduce:

Access the front page of the website by navigating to beattide.herokuapp.com

Expected behavior:

"Loading" message appears while front page content is fetched.

Actual behavior:

Front page content is loaded to begin with, then replaced with a loading message, then content appears again. AJAX

**Comment by rigsbyt** [comment]
Only happens sometimes--possibly on slow connections.

**Comment by rigsbyt** [comment]
Alex fixed.
