### ISSUE TITLE
On "Your Subscriptions" page, unsubscribing looks like unsubscribes all.

### ISSUE THREAD

**Issue by bkw7** [djmailhot/BeatTide#82]
Description: When unsubscribing from a user on the "Your Subscriptions" page, it looks like you end up subscribing from every user.

To reproduce: Sign in to BeatTide and navigate to the "Your Subscriptions" page.  Unsubscribe from a user and notice that all of the buttons change from "unsubscribe" to "subscribe".  

Expected Functionality: Either the user that is being unsubscribed to is removed from the list, or it only says "subscribe" next to their name and not the other people that you are still subscribed to.

I think it is pretty much a UI bug, since if the page is refreshed the users for which you clicked "unsubscribe" on disappear.

**Comment by rigsbyt** [comment]
Fixed.
