### ISSUE TITLE
Cannot access pages through going to URL.

### ISSUE THREAD

**Issue by bkw7** [djmailhot/BeatTide#83]
Description: Pages cannot be accessed by going to their corresponding URL after you are logged in.  

To Reproduce: Sign in to BeatTide, then enter the URL (localhost:3000 or beattide.herokuapp.com)/users/1.  Also doesn't work with pages like /faq.

Expected Functionality: Should take you to the corresponding page.

Actual Functionality: Redirects you to the homepage, and does some weird things with the URL.

**Comment by alexdmiller** [comment]
The URL must include the "#!". If you navigate to a page, bookmark it,
and attempt to return to it later, this will work. If the user
manually deletes parts of the URL (the #!) and then tries to navigate
to the URL, they shouldn't expect our app to work.

On Sat, Mar 10, 2012 at 11:23 AM, bkw7
reply@reply.github.com
wrote:
