### ISSUE TITLE
Can go to FAQ/About/Tutorial pages before signing in.

### ISSUE THREAD

**Issue by bkw7** [djmailhot/BeatTide#84]
Description: By clicking on the links at the bottom of the page, can go to the FAQ, About, and Tutorial pages before actually signing in.

To Reproduce: Go to the signin page of BeatTide without being signed in.  Click on FAQ, About, or Tutorial.

Expected Result: Should redirect you to the home page?

Actual Result: Takes you to the FAQ/Tutorial/About page.

I'm not sure if we actually want to worry about this, it might be a good thing for the user to be able to see these.  It just isn't consistent with our "none of the site can be accessed without signing in" philosophy, so I wanted to bring it up.

**Comment by mwinstanley** [comment]
I think this is perfect behavior! We should allow the user to read the FAQ before deciding whether to join.

**Comment by bkw7** [comment]
Alright great!
